"""empty message

Revision ID: fb133ea5bec1
Revises: 
Create Date: 2023-06-08 14:27:16.893317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb133ea5bec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_nm', sa.String(length=100), nullable=True),
    sa.Column('mid_nm', sa.String(length=100), nullable=True),
    sa.Column('last_nm', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('add_st', sa.String(length=255), nullable=True),
    sa.Column('add_st_two', sa.String(length=255), nullable=True),
    sa.Column('add_city', sa.String(length=100), nullable=True),
    sa.Column('add_prov', sa.String(length=100), nullable=True),
    sa.Column('add_zip', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('phn_num', sa.String(length=20), nullable=True),
    sa.Column('linkedin', sa.String(length=100), nullable=True),
    sa.Column('resume_file', sa.String(length=100), nullable=True),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_app')
    # ### end Alembic commands ###
